# Generated by Django 5.2.7 on 2025-10-21 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('fullname', models.CharField(max_length=128)),
                ('role', models.CharField(default='user', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=128)),
                ('new_name', models.CharField(blank=True, max_length=128, null=True)),
                ('comment', models.CharField(max_length=128)),
                ('size', models.BigIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_column='upload_date')),
                ('last_download_date', models.DateTimeField(blank=True, db_column='last_download_date', null=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('token', models.CharField(blank=True, max_length=32, null=True)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('id_user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='storages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'storage',
            },
        ),
    ]
